theme: events
baseurl: https://algo.ulb.be/events/
languageCode: en-us
title: Algo Events
buildFuture: true

#permalinks:
  #past: /:year/:month/:day/:title

taxonomies:
  tag: tags
  author: authors
  speaker: speakers

outputs:
  home:
    - HTML
    - RSS
    - Calendar
    - JSON
  section:
    - HTML
    - RSS
    - Calendar
  page:
    - HTML
    - Calendar
  taxonomy:
    - HTML
    - RSS
    - Calendar
  taxonomyTerm:
    - HTML

params:
  logo:
    src: https://cdn.jsdelivr.net/gh/aureooms-ulb/logo/files/ulb-logo-blue-square.svg
    alt: ULB
  organizer: 'CN="Aurélien Ooms":mailto:info@math.blog.aurelienooms.be'
  hostname: algo.ulb.be
  editURL: https://github.com/ulb/algo-events
  cards:
    taxonomies:
      - speakers
  nav:
    sections:
      - meetups
      - seminars
      - lunches
    taxonomies:
      - tags
      - speakers
  calendar:
    tzid: Europe/Brussels
    status:
      - CONFIRMED # Indicates event is definite.
      - TENTATIVE # Indicates event is tentative.
      - CANCELLED # Indicates event was cancelled.
    classification:
      - PUBLIC
      - PRIVATE
      - CONFIDENTIAL
